services:
  vrcomandaapi:
    build: .
    container_name: vrcomandaapi
    restart: unless-stopped
    ports:
      - "28232:28232"
    environment:
      HTTP_PORT: ":28232"
      MONGO_URI: "mongodb://root:example@vrintegrador-db:26017/?directConnection=true&authSource=admin"
      MONGO_DATABASE: "pdv"
      SQLITE_PATH: "/app/data/vrcomanda.db"
    volumes:
      - vrcomanda_data:/app/data
    networks:
      - vr_network

volumes:
  vrcomanda_data:

networks:
  vr_network:
    external: true
    name: vrintegradormaster_vrintegrador-net
